---
apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: WorkloadRegistration
metadata:
  name: appsso-starter-java
  labels:
    app.kubernetes.io/part-of: appsso-starter-java
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  workloadRef:
    name: test-workload-name
    namespace: test-workload-namespace
  authServerSelector:
    matchLabels:
      name: authserver-sample
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: live-update
      value: "true"
  source:
    git:
      url: https://github.com/sarahwalther/app-sso-starter-simple.git
      ref:
        branch: main
